name: FB Security Pipeline

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  
  trivy_container_scan:
    runs-on:
      ubuntu-latest
    needs: 'setup'
    steps:
      - uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'bkimminich/juice-shop'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  trivy_dependency_scan:
    needs: 'setup'
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: juice-shop/juice-shop
          path: .
          fetch-depth: 1
      - run:
          npm install
          npm install --package-lock-only
      - uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
  gitleaks_scan:
    runs-on:
      ubuntu-latest
    needs:
      'setup'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: juice-shop/juice-shop
          path: .
          fetch-depth: 1
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  sbom_scan:    
    runs-on:
      ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0
        with:
          image: bkimminich/juice-shop
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"
      - uses: anchore/scan-action@v7
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          fail-build: false
  report:
    runs-on:
      ubuntu-latest
    needs: ['trivy_container_scan','sbom_scan','trivy_dependency_scan','gitleaks_scan']  
    if: always()
    steps:
      - run:
          echo "SBOM Check- ${{needs.sbom_scan.result}}"
          echo "Trivy Container Scan- ${{needs.trivy_container_scan.result}}"
          echo "Trivy Dependency Scan- ${{needs.trivy_dependency_scan.result}}"
          echo "Gitleaks Scan- ${{needs.gitleaks_scan.result}}"